name: Keep Alive
on:
  schedule:
    - cron: "0 2 1 * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@github.com"
          git commit --allow-empty -m "Auto keepalive commit"
          git push
